#!/bin/bash

set -ex

VGA=`lspci -nnk | grep VGA\ compatible\ controller | grep -oP '\[\K[^\]]+' | tail +3`

VGA_AUDIO=`lspci -nnk | grep High\ Definition\ Audio\ Controller | grep -oP '\[\K[^\]]+' | tail +4`

echo VGA is $VGA, VGA AUDIO is $VGA_AUDIO

sudo sed \
  -e "s/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet pcie_acs_override=downstream intel_iommu=on pci-stub.ids=$VGA,$VGA_AUDIO\"/g" \
  -i /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg

sudo sed \
  -e 's/MODULES=.*/MODULES=(pci-stub)/g' \
  -i /etc/mkinitcpio.conf
sudo mkinitcpio -p linux

gpg --recv-keys A5E9288C4FA415FA | true

git clone https://aur.archlinux.org/linux-vfio.git
cd linux-vfio
yes | makepkg -sri 
cd -

#sudo pacman -S qemu dmidecode dnsmasq firewalld rpmextract

chmod +x vfio-bind
sudo cp vfio-bind /usr/bin/

chmod +x windows
sudo cp windows /usr/local/bin/

sudo vfio-bind 0000:01:00.0 0000:01:00.1

